import { createFileRoute } from "@tanstack/react-router";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useRef,useState } from "react";
import { Camera,Clock,Loader2,MapPin,MessageSquare,Navigation2,PackageCheck,Play,RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { QUICK_MESSAGE_KEYS,quickMessageText } from "@/lib/driver-quick-messages";
import { getMyActiveDeliveryBlock,listDeliveryBlockMessages,sendDeliveryBlockMessage,startDeliveryBlock,updateDeliveryBlockStop } from "@/lib/delivery-block-operations.functions";

export const Route=createFileRoute("/_authenticated/repartidor/bloque")({head:()=>({meta:[{title:"Lote activo — Repartidor Hazorex"},{name:"description",content:"Ruta y paradas del lote asignado."},{property:"og:title",content:"Lote activo — Repartidor Hazorex"},{property:"og:description",content:"Ruta privada del lote asignado."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex"}]}),component:ActiveBlockPage});

function addressOf(stop:any){const a=stop.store_orders?.direccion_envio??{};return [a.street??a.address,a.apt,a.city,a.state,a.zip].filter(Boolean).join(", ");}
function ActiveBlockPage(){
 const qc=useQueryClient(); const load=useServerFn(getMyActiveDeliveryBlock); const startFn=useServerFn(startDeliveryBlock); const updateFn=useServerFn(updateDeliveryBlockStop); const sendFn=useServerFn(sendDeliveryBlockMessage); const messagesFn=useServerFn(listDeliveryBlockMessages);
 const q=useQuery({queryKey:["delivery-block","active"],queryFn:()=>load(),refetchInterval:15000}); const [busy,setBusy]=useState<string|null>(null); const [photoStop,setPhotoStop]=useState<any|null>(null); const fileRef=useRef<HTMLInputElement>(null);
 const mutation=useMutation({mutationFn:async(fn:()=>Promise<unknown>)=>fn(),onSuccess:()=>{qc.invalidateQueries({queryKey:["delivery-block"]});},onError:(e:Error)=>toast.error(e.message)});
 async function upload(stop:any,file?:File){if(!file)return;setBusy(stop.id);try{const {supabase}=await import("@/integrations/supabase/client");const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Inicia sesión de nuevo");const ext=(file.name.split(".").pop()||"jpg").slice(0,5);const path=`${u.user.id}/${stop.store_order_id}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("delivery-photos").upload(path,file,{contentType:file.type||"image/jpeg"});if(error)throw error;const res=await updateFn({data:{stopId:stop.id,action:"delivered",photoPath:path,note:"Foto de entrega"}});toast.success(res.blockComplete?(res.paymentSent?"Lote completado y pago enviado.":`Lote completado. ${res.paymentError??"Pago pendiente."}`):"Entrega confirmada.");await qc.invalidateQueries({queryKey:["delivery-block"]});}catch(e){toast.error(e instanceof Error?e.message:"No se pudo entregar");}finally{setBusy(null);setPhotoStop(null);}}
 if(q.isLoading)return <div className="grid min-h-64 place-items-center"><Loader2 className="size-6 animate-spin"/></div>; if(!q.data)return <main className="mx-auto max-w-2xl p-6"><h1 className="text-2xl font-bold">Lote activo</h1><p className="mt-2 text-muted-foreground">No tienes un lote asignado ahora.</p></main>;
 const {block,stops}=q.data;return <main className="mx-auto max-w-2xl space-y-4 p-4"><input ref={fileRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={(e)=>upload(photoStop,e.target.files?.[0])}/><header className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{block.zone_name}</h1><p className="text-sm text-muted-foreground">{stops.length} paradas · {block.estimated_minutes} min · ${(Number(block.committed_pay)+Number(block.tips_total)).toFixed(2)}</p></div><Button size="icon" variant="ghost" title="Actualizar" onClick={()=>q.refetch()}><RefreshCw className="size-4"/></Button></header>{block.status==="assigned"&&<Button className="w-full" onClick={()=>mutation.mutate(()=>startFn({data:{blockId:block.id}}))}><Play className="mr-2 size-4"/>Salir y avisar hora estimada</Button>}<section className="space-y-3">{stops.map((stop:any)=><StopCard key={stop.id} stop={stop} busy={busy===stop.id} active={block.status==="active"} onAction={(action)=>{setBusy(stop.id);mutation.mutate(()=>updateFn({data:{stopId:stop.id,action}}),{onSettled:()=>setBusy(null)})}} onPhoto={()=>{setPhotoStop(stop);fileRef.current?.click()}} onMessage={async(key)=>{const body=quickMessageText(key,"es");await sendFn({data:{orderId:stop.store_order_id,messageKey:key,body}});toast.success("Mensaje enviado");}} messagesFn={messagesFn}/>)}</section></main>;
}
function StopCard({stop,busy,active,onAction,onPhoto,onMessage,messagesFn}:{stop:any;busy:boolean;active:boolean;onAction:(a:"arrived"|"waiting"|"returned")=>void;onPhoto:()=>void;onMessage:(k:any)=>Promise<void>;messagesFn:any}){const [showMessages,setShowMessages]=useState(false);const messages=useQuery({queryKey:["delivery-block","messages",stop.store_order_id],queryFn:()=>messagesFn({data:{orderId:stop.store_order_id}}),enabled:showMessages});const address=addressOf(stop);const maps=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}&travelmode=driving`;return <Card><CardContent className="space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">Parada {stop.sequence_number} · {stop.store_orders?.businesses?.business_name??"Tienda"}</p><p className="text-sm text-muted-foreground">{stop.size_label}{stop.heavy_items?" · pesado":""}{stop.has_cold_items?" · frío":""}{stop.door_service!=="lobby"?" · puerta":""}</p></div><span className="text-xs font-semibold uppercase">{stop.status}</span></div><p className="flex items-start gap-2 text-sm"><MapPin className="mt-0.5 size-4 shrink-0"/>{address}</p>{stop.eta&&<p className="flex items-center gap-2 text-sm"><Clock className="size-4"/>ETA {new Date(stop.eta).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p>}<a href={maps} target="_blank" rel="noopener" className="flex h-11 items-center justify-center rounded-md border text-sm font-semibold"><Navigation2 className="mr-2 size-4"/>Abrir en Google Maps</a><div className="grid grid-cols-2 gap-2"><Button variant="outline" disabled={!active||busy} onClick={()=>onAction("arrived")}>Llegué</Button><Button variant="outline" disabled={!active||busy} onClick={()=>onAction("waiting")}>Esperando</Button><Button disabled={!active||busy} onClick={onPhoto}><Camera className="mr-2 size-4"/>Entregar</Button><Button variant="outline" disabled={!active||busy||!stop.requires_safe_return} onClick={()=>onAction("returned")}>Devolver</Button></div><Button variant="ghost" className="w-full" onClick={()=>setShowMessages(!showMessages)}><MessageSquare className="mr-2 size-4"/>Mensajes con un toque</Button>{showMessages&&<div className="space-y-2">{QUICK_MESSAGE_KEYS.map((key)=><Button key={key} variant="outline" className="w-full justify-start" onClick={()=>onMessage(key)}>{quickMessageText(key,"es")}</Button>)}{(messages.data??[]).map((m:any)=><p key={m.id} className="rounded-md bg-muted p-2 text-sm">{m.body}</p>)}</div>}</CardContent></Card>}