/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SweepstakesRulesRouteImport } from './routes/sweepstakes-rules'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RuletaRouteImport } from './routes/ruleta'
import { Route as RepartidoresRouteImport } from './routes/repartidores'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReelReelIdRouteImport } from './routes/reel.$reelId'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as NegociosRegistroRouteImport } from './routes/negocios.registro'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AdminSweepstakesRouteImport } from './routes/admin.sweepstakes'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AuthenticatedSuggestionsRouteImport } from './routes/_authenticated/suggestions'
import { Route as AuthenticatedRepartidorRouteImport } from './routes/_authenticated/repartidor'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedRepartidorIndexRouteImport } from './routes/_authenticated/repartidor.index'
import { Route as AuthenticatedNegocioIndexRouteImport } from './routes/_authenticated/negocio.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicDomainCheckRouteImport } from './routes/api/public/domain-check'
import { Route as AdminSweepstakesWinnersRouteImport } from './routes/admin.sweepstakes.winners'
import { Route as AuthenticatedRepartidorWalletRouteImport } from './routes/_authenticated/repartidor.wallet'
import { Route as AuthenticatedRepartidorOnboardingRouteImport } from './routes/_authenticated/repartidor.onboarding'
import { Route as AuthenticatedRepartidorFacturasRouteImport } from './routes/_authenticated/repartidor.facturas'
import { Route as AuthenticatedRepartidorCalificacionesRouteImport } from './routes/_authenticated/repartidor.calificaciones'
import { Route as AuthenticatedNegocioProductosRouteImport } from './routes/_authenticated/negocio.productos'
import { Route as AuthenticatedNegocioOfertasRouteImport } from './routes/_authenticated/negocio.ofertas'
import { Route as AuthenticatedClaimDrawDateRouteImport } from './routes/_authenticated/claim.$drawDate'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSuggestionsRouteImport } from './routes/_authenticated/admin.suggestions'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminRepartidoresRouteImport } from './routes/_authenticated/admin.repartidores'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin.live'
import { Route as AuthenticatedAdminDeliveriesRouteImport } from './routes/_authenticated/admin.deliveries'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTestDrawTickRouteImport } from './routes/api/public/hooks/test-draw-tick'
import { Route as ApiPublicHooksSecurityAlertRouteImport } from './routes/api/public/hooks/security-alert'
import { Route as ApiPublicHooksRunDailyDrawRouteImport } from './routes/api/public/hooks/run-daily-draw'
import { Route as ApiPublicHooksNotifyWinnerRouteImport } from './routes/api/public/hooks/notify-winner'
import { Route as ApiPublicHooksNotifyPreDrawRouteImport } from './routes/api/public/hooks/notify-pre-draw'
import { Route as ApiPublicHooksBackupPruneRouteImport } from './routes/api/public/hooks/backup-prune'
import { Route as ApiPublicHooksBackupCsvRouteImport } from './routes/api/public/hooks/backup-csv'
import { Route as AuthenticatedPedidoIdSeguimientoRouteImport } from './routes/_authenticated/pedido.$id.seguimiento'
import { Route as AuthenticatedPedidoIdCalificarRouteImport } from './routes/_authenticated/pedido.$id.calificar'
import { Route as AuthenticatedRepartidorPedidoIdResumenRouteImport } from './routes/_authenticated/repartidor.pedido.$id.resumen'
import { Route as AuthenticatedRepartidorPedidoIdNavegacionRouteImport } from './routes/_authenticated/repartidor.pedido.$id.navegacion'
import { Route as AuthenticatedRepartidorPedidoIdCompletadoRouteImport } from './routes/_authenticated/repartidor.pedido.$id.completado'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepstakesRulesRoute = SweepstakesRulesRouteImport.update({
  id: '/sweepstakes-rules',
  path: '/sweepstakes-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RuletaRoute = RuletaRouteImport.update({
  id: '/ruleta',
  path: '/ruleta',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidoresRoute = RepartidoresRouteImport.update({
  id: '/repartidores',
  path: '/repartidores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelReelIdRoute = ReelReelIdRouteImport.update({
  id: '/reel/$reelId',
  path: '/reel/$reelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRegistroRoute = NegociosRegistroRouteImport.update({
  id: '/negocios/registro',
  path: '/negocios/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSweepstakesRoute = AdminSweepstakesRouteImport.update({
  id: '/admin/sweepstakes',
  path: '/admin/sweepstakes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuggestionsRoute =
  AuthenticatedSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepartidorRoute = AuthenticatedRepartidorRouteImport.update({
  id: '/repartidor',
  path: '/repartidor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepartidorIndexRoute =
  AuthenticatedRepartidorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedNegocioIndexRoute =
  AuthenticatedNegocioIndexRouteImport.update({
    id: '/negocio/',
    path: '/negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDomainCheckRoute = ApiPublicDomainCheckRouteImport.update({
  id: '/api/public/domain-check',
  path: '/api/public/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSweepstakesWinnersRoute = AdminSweepstakesWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminSweepstakesRoute,
} as any)
const AuthenticatedRepartidorWalletRoute =
  AuthenticatedRepartidorWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedRepartidorOnboardingRoute =
  AuthenticatedRepartidorOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedRepartidorFacturasRoute =
  AuthenticatedRepartidorFacturasRouteImport.update({
    id: '/facturas',
    path: '/facturas',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedRepartidorCalificacionesRoute =
  AuthenticatedRepartidorCalificacionesRouteImport.update({
    id: '/calificaciones',
    path: '/calificaciones',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedNegocioProductosRoute =
  AuthenticatedNegocioProductosRouteImport.update({
    id: '/negocio/productos',
    path: '/negocio/productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioOfertasRoute =
  AuthenticatedNegocioOfertasRouteImport.update({
    id: '/negocio/ofertas',
    path: '/negocio/ofertas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimDrawDateRoute =
  AuthenticatedClaimDrawDateRouteImport.update({
    id: '/claim/$drawDate',
    path: '/claim/$drawDate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSuggestionsRoute =
  AuthenticatedAdminSuggestionsRouteImport.update({
    id: '/admin/suggestions',
    path: '/admin/suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRepartidoresRoute =
  AuthenticatedAdminRepartidoresRouteImport.update({
    id: '/admin/repartidores',
    path: '/admin/repartidores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDeliveriesRoute =
  AuthenticatedAdminDeliveriesRouteImport.update({
    id: '/admin/deliveries',
    path: '/admin/deliveries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestDrawTickRoute =
  ApiPublicHooksTestDrawTickRouteImport.update({
    id: '/api/public/hooks/test-draw-tick',
    path: '/api/public/hooks/test-draw-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSecurityAlertRoute =
  ApiPublicHooksSecurityAlertRouteImport.update({
    id: '/api/public/hooks/security-alert',
    path: '/api/public/hooks/security-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunDailyDrawRoute =
  ApiPublicHooksRunDailyDrawRouteImport.update({
    id: '/api/public/hooks/run-daily-draw',
    path: '/api/public/hooks/run-daily-draw',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyWinnerRoute =
  ApiPublicHooksNotifyWinnerRouteImport.update({
    id: '/api/public/hooks/notify-winner',
    path: '/api/public/hooks/notify-winner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyPreDrawRoute =
  ApiPublicHooksNotifyPreDrawRouteImport.update({
    id: '/api/public/hooks/notify-pre-draw',
    path: '/api/public/hooks/notify-pre-draw',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackupPruneRoute =
  ApiPublicHooksBackupPruneRouteImport.update({
    id: '/api/public/hooks/backup-prune',
    path: '/api/public/hooks/backup-prune',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackupCsvRoute = ApiPublicHooksBackupCsvRouteImport.update({
  id: '/api/public/hooks/backup-csv',
  path: '/api/public/hooks/backup-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidoIdSeguimientoRoute =
  AuthenticatedPedidoIdSeguimientoRouteImport.update({
    id: '/pedido/$id/seguimiento',
    path: '/pedido/$id/seguimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidoIdCalificarRoute =
  AuthenticatedPedidoIdCalificarRouteImport.update({
    id: '/pedido/$id/calificar',
    path: '/pedido/$id/calificar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepartidorPedidoIdResumenRoute =
  AuthenticatedRepartidorPedidoIdResumenRouteImport.update({
    id: '/pedido/$id/resumen',
    path: '/pedido/$id/resumen',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedRepartidorPedidoIdNavegacionRoute =
  AuthenticatedRepartidorPedidoIdNavegacionRouteImport.update({
    id: '/pedido/$id/navegacion',
    path: '/pedido/$id/navegacion',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)
const AuthenticatedRepartidorPedidoIdCompletadoRoute =
  AuthenticatedRepartidorPedidoIdCompletadoRouteImport.update({
    id: '/pedido/$id/completado',
    path: '/pedido/$id/completado',
    getParentRoute: () => AuthenticatedRepartidorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/demo': typeof DemoRoute
  '/domains': typeof DomainsRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/historial': typeof HistorialRoute
  '/menu': typeof MenuRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/repartidores': typeof RepartidoresRoute
  '/ruleta': typeof RuletaRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/sweepstakes-rules': typeof SweepstakesRulesRoute
  '/terminos': typeof TerminosRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/repartidor': typeof AuthenticatedRepartidorRouteWithChildren
  '/suggestions': typeof AuthenticatedSuggestionsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sweepstakes': typeof AdminSweepstakesRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/negocios/registro': typeof NegociosRegistroRoute
  '/product/$handle': typeof ProductHandleRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/repartidores': typeof AuthenticatedAdminRepartidoresRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/claim/$drawDate': typeof AuthenticatedClaimDrawDateRoute
  '/negocio/ofertas': typeof AuthenticatedNegocioOfertasRoute
  '/negocio/productos': typeof AuthenticatedNegocioProductosRoute
  '/repartidor/calificaciones': typeof AuthenticatedRepartidorCalificacionesRoute
  '/repartidor/facturas': typeof AuthenticatedRepartidorFacturasRoute
  '/repartidor/onboarding': typeof AuthenticatedRepartidorOnboardingRoute
  '/repartidor/wallet': typeof AuthenticatedRepartidorWalletRoute
  '/admin/sweepstakes/winners': typeof AdminSweepstakesWinnersRoute
  '/api/public/domain-check': typeof ApiPublicDomainCheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/negocio/': typeof AuthenticatedNegocioIndexRoute
  '/repartidor/': typeof AuthenticatedRepartidorIndexRoute
  '/pedido/$id/calificar': typeof AuthenticatedPedidoIdCalificarRoute
  '/pedido/$id/seguimiento': typeof AuthenticatedPedidoIdSeguimientoRoute
  '/api/public/hooks/backup-csv': typeof ApiPublicHooksBackupCsvRoute
  '/api/public/hooks/backup-prune': typeof ApiPublicHooksBackupPruneRoute
  '/api/public/hooks/notify-pre-draw': typeof ApiPublicHooksNotifyPreDrawRoute
  '/api/public/hooks/notify-winner': typeof ApiPublicHooksNotifyWinnerRoute
  '/api/public/hooks/run-daily-draw': typeof ApiPublicHooksRunDailyDrawRoute
  '/api/public/hooks/security-alert': typeof ApiPublicHooksSecurityAlertRoute
  '/api/public/hooks/test-draw-tick': typeof ApiPublicHooksTestDrawTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/repartidor/pedido/$id/completado': typeof AuthenticatedRepartidorPedidoIdCompletadoRoute
  '/repartidor/pedido/$id/navegacion': typeof AuthenticatedRepartidorPedidoIdNavegacionRoute
  '/repartidor/pedido/$id/resumen': typeof AuthenticatedRepartidorPedidoIdResumenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/demo': typeof DemoRoute
  '/domains': typeof DomainsRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/historial': typeof HistorialRoute
  '/menu': typeof MenuRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/repartidores': typeof RepartidoresRoute
  '/ruleta': typeof RuletaRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/sweepstakes-rules': typeof SweepstakesRulesRoute
  '/terminos': typeof TerminosRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/suggestions': typeof AuthenticatedSuggestionsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sweepstakes': typeof AdminSweepstakesRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/negocios/registro': typeof NegociosRegistroRoute
  '/product/$handle': typeof ProductHandleRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/repartidores': typeof AuthenticatedAdminRepartidoresRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/claim/$drawDate': typeof AuthenticatedClaimDrawDateRoute
  '/negocio/ofertas': typeof AuthenticatedNegocioOfertasRoute
  '/negocio/productos': typeof AuthenticatedNegocioProductosRoute
  '/repartidor/calificaciones': typeof AuthenticatedRepartidorCalificacionesRoute
  '/repartidor/facturas': typeof AuthenticatedRepartidorFacturasRoute
  '/repartidor/onboarding': typeof AuthenticatedRepartidorOnboardingRoute
  '/repartidor/wallet': typeof AuthenticatedRepartidorWalletRoute
  '/admin/sweepstakes/winners': typeof AdminSweepstakesWinnersRoute
  '/api/public/domain-check': typeof ApiPublicDomainCheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/negocio': typeof AuthenticatedNegocioIndexRoute
  '/repartidor': typeof AuthenticatedRepartidorIndexRoute
  '/pedido/$id/calificar': typeof AuthenticatedPedidoIdCalificarRoute
  '/pedido/$id/seguimiento': typeof AuthenticatedPedidoIdSeguimientoRoute
  '/api/public/hooks/backup-csv': typeof ApiPublicHooksBackupCsvRoute
  '/api/public/hooks/backup-prune': typeof ApiPublicHooksBackupPruneRoute
  '/api/public/hooks/notify-pre-draw': typeof ApiPublicHooksNotifyPreDrawRoute
  '/api/public/hooks/notify-winner': typeof ApiPublicHooksNotifyWinnerRoute
  '/api/public/hooks/run-daily-draw': typeof ApiPublicHooksRunDailyDrawRoute
  '/api/public/hooks/security-alert': typeof ApiPublicHooksSecurityAlertRoute
  '/api/public/hooks/test-draw-tick': typeof ApiPublicHooksTestDrawTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/repartidor/pedido/$id/completado': typeof AuthenticatedRepartidorPedidoIdCompletadoRoute
  '/repartidor/pedido/$id/navegacion': typeof AuthenticatedRepartidorPedidoIdNavegacionRoute
  '/repartidor/pedido/$id/resumen': typeof AuthenticatedRepartidorPedidoIdResumenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/demo': typeof DemoRoute
  '/domains': typeof DomainsRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/historial': typeof HistorialRoute
  '/menu': typeof MenuRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/repartidores': typeof RepartidoresRoute
  '/ruleta': typeof RuletaRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/sweepstakes-rules': typeof SweepstakesRulesRoute
  '/terminos': typeof TerminosRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/repartidor': typeof AuthenticatedRepartidorRouteWithChildren
  '/_authenticated/suggestions': typeof AuthenticatedSuggestionsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/sweepstakes': typeof AdminSweepstakesRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/negocios/registro': typeof NegociosRegistroRoute
  '/product/$handle': typeof ProductHandleRoute
  '/reel/$reelId': typeof ReelReelIdRoute
  '/_authenticated/admin/deliveries': typeof AuthenticatedAdminDeliveriesRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/repartidores': typeof AuthenticatedAdminRepartidoresRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/suggestions': typeof AuthenticatedAdminSuggestionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/claim/$drawDate': typeof AuthenticatedClaimDrawDateRoute
  '/_authenticated/negocio/ofertas': typeof AuthenticatedNegocioOfertasRoute
  '/_authenticated/negocio/productos': typeof AuthenticatedNegocioProductosRoute
  '/_authenticated/repartidor/calificaciones': typeof AuthenticatedRepartidorCalificacionesRoute
  '/_authenticated/repartidor/facturas': typeof AuthenticatedRepartidorFacturasRoute
  '/_authenticated/repartidor/onboarding': typeof AuthenticatedRepartidorOnboardingRoute
  '/_authenticated/repartidor/wallet': typeof AuthenticatedRepartidorWalletRoute
  '/admin/sweepstakes/winners': typeof AdminSweepstakesWinnersRoute
  '/api/public/domain-check': typeof ApiPublicDomainCheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/negocio/': typeof AuthenticatedNegocioIndexRoute
  '/_authenticated/repartidor/': typeof AuthenticatedRepartidorIndexRoute
  '/_authenticated/pedido/$id/calificar': typeof AuthenticatedPedidoIdCalificarRoute
  '/_authenticated/pedido/$id/seguimiento': typeof AuthenticatedPedidoIdSeguimientoRoute
  '/api/public/hooks/backup-csv': typeof ApiPublicHooksBackupCsvRoute
  '/api/public/hooks/backup-prune': typeof ApiPublicHooksBackupPruneRoute
  '/api/public/hooks/notify-pre-draw': typeof ApiPublicHooksNotifyPreDrawRoute
  '/api/public/hooks/notify-winner': typeof ApiPublicHooksNotifyWinnerRoute
  '/api/public/hooks/run-daily-draw': typeof ApiPublicHooksRunDailyDrawRoute
  '/api/public/hooks/security-alert': typeof ApiPublicHooksSecurityAlertRoute
  '/api/public/hooks/test-draw-tick': typeof ApiPublicHooksTestDrawTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/repartidor/pedido/$id/completado': typeof AuthenticatedRepartidorPedidoIdCompletadoRoute
  '/_authenticated/repartidor/pedido/$id/navegacion': typeof AuthenticatedRepartidorPedidoIdNavegacionRoute
  '/_authenticated/repartidor/pedido/$id/resumen': typeof AuthenticatedRepartidorPedidoIdResumenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/demo'
    | '/domains'
    | '/donate'
    | '/explore'
    | '/historial'
    | '/menu'
    | '/privacidad'
    | '/profile'
    | '/repartidores'
    | '/ruleta'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/subscribe'
    | '/sweepstakes-rules'
    | '/terminos'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/deliveries'
    | '/repartidor'
    | '/suggestions'
    | '/admin/shipping'
    | '/admin/sweepstakes'
    | '/checkout/success'
    | '/email/unsubscribe'
    | '/negocios/registro'
    | '/product/$handle'
    | '/reel/$reelId'
    | '/admin/deliveries'
    | '/admin/live'
    | '/admin/repartidores'
    | '/admin/security'
    | '/admin/suggestions'
    | '/admin/support'
    | '/claim/$drawDate'
    | '/negocio/ofertas'
    | '/negocio/productos'
    | '/repartidor/calificaciones'
    | '/repartidor/facturas'
    | '/repartidor/onboarding'
    | '/repartidor/wallet'
    | '/admin/sweepstakes/winners'
    | '/api/public/domain-check'
    | '/lovable/email/suppression'
    | '/negocio/'
    | '/repartidor/'
    | '/pedido/$id/calificar'
    | '/pedido/$id/seguimiento'
    | '/api/public/hooks/backup-csv'
    | '/api/public/hooks/backup-prune'
    | '/api/public/hooks/notify-pre-draw'
    | '/api/public/hooks/notify-winner'
    | '/api/public/hooks/run-daily-draw'
    | '/api/public/hooks/security-alert'
    | '/api/public/hooks/test-draw-tick'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/repartidor/pedido/$id/completado'
    | '/repartidor/pedido/$id/navegacion'
    | '/repartidor/pedido/$id/resumen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/demo'
    | '/domains'
    | '/donate'
    | '/explore'
    | '/historial'
    | '/menu'
    | '/privacidad'
    | '/profile'
    | '/repartidores'
    | '/ruleta'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/subscribe'
    | '/sweepstakes-rules'
    | '/terminos'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/deliveries'
    | '/suggestions'
    | '/admin/shipping'
    | '/admin/sweepstakes'
    | '/checkout/success'
    | '/email/unsubscribe'
    | '/negocios/registro'
    | '/product/$handle'
    | '/reel/$reelId'
    | '/admin/deliveries'
    | '/admin/live'
    | '/admin/repartidores'
    | '/admin/security'
    | '/admin/suggestions'
    | '/admin/support'
    | '/claim/$drawDate'
    | '/negocio/ofertas'
    | '/negocio/productos'
    | '/repartidor/calificaciones'
    | '/repartidor/facturas'
    | '/repartidor/onboarding'
    | '/repartidor/wallet'
    | '/admin/sweepstakes/winners'
    | '/api/public/domain-check'
    | '/lovable/email/suppression'
    | '/negocio'
    | '/repartidor'
    | '/pedido/$id/calificar'
    | '/pedido/$id/seguimiento'
    | '/api/public/hooks/backup-csv'
    | '/api/public/hooks/backup-prune'
    | '/api/public/hooks/notify-pre-draw'
    | '/api/public/hooks/notify-winner'
    | '/api/public/hooks/run-daily-draw'
    | '/api/public/hooks/security-alert'
    | '/api/public/hooks/test-draw-tick'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/repartidor/pedido/$id/completado'
    | '/repartidor/pedido/$id/navegacion'
    | '/repartidor/pedido/$id/resumen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/demo'
    | '/domains'
    | '/donate'
    | '/explore'
    | '/historial'
    | '/menu'
    | '/privacidad'
    | '/profile'
    | '/repartidores'
    | '/ruleta'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/subscribe'
    | '/sweepstakes-rules'
    | '/terminos'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/_authenticated/deliveries'
    | '/_authenticated/repartidor'
    | '/_authenticated/suggestions'
    | '/admin/shipping'
    | '/admin/sweepstakes'
    | '/checkout/success'
    | '/email/unsubscribe'
    | '/negocios/registro'
    | '/product/$handle'
    | '/reel/$reelId'
    | '/_authenticated/admin/deliveries'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/repartidores'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/suggestions'
    | '/_authenticated/admin/support'
    | '/_authenticated/claim/$drawDate'
    | '/_authenticated/negocio/ofertas'
    | '/_authenticated/negocio/productos'
    | '/_authenticated/repartidor/calificaciones'
    | '/_authenticated/repartidor/facturas'
    | '/_authenticated/repartidor/onboarding'
    | '/_authenticated/repartidor/wallet'
    | '/admin/sweepstakes/winners'
    | '/api/public/domain-check'
    | '/lovable/email/suppression'
    | '/_authenticated/negocio/'
    | '/_authenticated/repartidor/'
    | '/_authenticated/pedido/$id/calificar'
    | '/_authenticated/pedido/$id/seguimiento'
    | '/api/public/hooks/backup-csv'
    | '/api/public/hooks/backup-prune'
    | '/api/public/hooks/notify-pre-draw'
    | '/api/public/hooks/notify-winner'
    | '/api/public/hooks/run-daily-draw'
    | '/api/public/hooks/security-alert'
    | '/api/public/hooks/test-draw-tick'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/repartidor/pedido/$id/completado'
    | '/_authenticated/repartidor/pedido/$id/navegacion'
    | '/_authenticated/repartidor/pedido/$id/resumen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  DemoRoute: typeof DemoRoute
  DomainsRoute: typeof DomainsRoute
  DonateRoute: typeof DonateRoute
  ExploreRoute: typeof ExploreRoute
  HistorialRoute: typeof HistorialRoute
  MenuRoute: typeof MenuRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProfileRoute: typeof ProfileRoute
  RepartidoresRoute: typeof RepartidoresRoute
  RuletaRoute: typeof RuletaRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  SweepstakesRulesRoute: typeof SweepstakesRulesRoute
  TerminosRoute: typeof TerminosRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminSweepstakesRoute: typeof AdminSweepstakesRouteWithChildren
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  NegociosRegistroRoute: typeof NegociosRegistroRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ReelReelIdRoute: typeof ReelReelIdRoute
  ApiPublicDomainCheckRoute: typeof ApiPublicDomainCheckRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksBackupCsvRoute: typeof ApiPublicHooksBackupCsvRoute
  ApiPublicHooksBackupPruneRoute: typeof ApiPublicHooksBackupPruneRoute
  ApiPublicHooksNotifyPreDrawRoute: typeof ApiPublicHooksNotifyPreDrawRoute
  ApiPublicHooksNotifyWinnerRoute: typeof ApiPublicHooksNotifyWinnerRoute
  ApiPublicHooksRunDailyDrawRoute: typeof ApiPublicHooksRunDailyDrawRoute
  ApiPublicHooksSecurityAlertRoute: typeof ApiPublicHooksSecurityAlertRoute
  ApiPublicHooksTestDrawTickRoute: typeof ApiPublicHooksTestDrawTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweepstakes-rules': {
      id: '/sweepstakes-rules'
      path: '/sweepstakes-rules'
      fullPath: '/sweepstakes-rules'
      preLoaderRoute: typeof SweepstakesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleta': {
      id: '/ruleta'
      path: '/ruleta'
      fullPath: '/ruleta'
      preLoaderRoute: typeof RuletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidores': {
      id: '/repartidores'
      path: '/repartidores'
      fullPath: '/repartidores'
      preLoaderRoute: typeof RepartidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel/$reelId': {
      id: '/reel/$reelId'
      path: '/reel/$reelId'
      fullPath: '/reel/$reelId'
      preLoaderRoute: typeof ReelReelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/registro': {
      id: '/negocios/registro'
      path: '/negocios/registro'
      fullPath: '/negocios/registro'
      preLoaderRoute: typeof NegociosRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sweepstakes': {
      id: '/admin/sweepstakes'
      path: '/admin/sweepstakes'
      fullPath: '/admin/sweepstakes'
      preLoaderRoute: typeof AdminSweepstakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suggestions': {
      id: '/_authenticated/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof AuthenticatedSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repartidor': {
      id: '/_authenticated/repartidor'
      path: '/repartidor'
      fullPath: '/repartidor'
      preLoaderRoute: typeof AuthenticatedRepartidorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repartidor/': {
      id: '/_authenticated/repartidor/'
      path: '/'
      fullPath: '/repartidor/'
      preLoaderRoute: typeof AuthenticatedRepartidorIndexRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/negocio/': {
      id: '/_authenticated/negocio/'
      path: '/negocio'
      fullPath: '/negocio/'
      preLoaderRoute: typeof AuthenticatedNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/domain-check': {
      id: '/api/public/domain-check'
      path: '/api/public/domain-check'
      fullPath: '/api/public/domain-check'
      preLoaderRoute: typeof ApiPublicDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sweepstakes/winners': {
      id: '/admin/sweepstakes/winners'
      path: '/winners'
      fullPath: '/admin/sweepstakes/winners'
      preLoaderRoute: typeof AdminSweepstakesWinnersRouteImport
      parentRoute: typeof AdminSweepstakesRoute
    }
    '/_authenticated/repartidor/wallet': {
      id: '/_authenticated/repartidor/wallet'
      path: '/wallet'
      fullPath: '/repartidor/wallet'
      preLoaderRoute: typeof AuthenticatedRepartidorWalletRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/repartidor/onboarding': {
      id: '/_authenticated/repartidor/onboarding'
      path: '/onboarding'
      fullPath: '/repartidor/onboarding'
      preLoaderRoute: typeof AuthenticatedRepartidorOnboardingRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/repartidor/facturas': {
      id: '/_authenticated/repartidor/facturas'
      path: '/facturas'
      fullPath: '/repartidor/facturas'
      preLoaderRoute: typeof AuthenticatedRepartidorFacturasRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/repartidor/calificaciones': {
      id: '/_authenticated/repartidor/calificaciones'
      path: '/calificaciones'
      fullPath: '/repartidor/calificaciones'
      preLoaderRoute: typeof AuthenticatedRepartidorCalificacionesRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/negocio/productos': {
      id: '/_authenticated/negocio/productos'
      path: '/negocio/productos'
      fullPath: '/negocio/productos'
      preLoaderRoute: typeof AuthenticatedNegocioProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/ofertas': {
      id: '/_authenticated/negocio/ofertas'
      path: '/negocio/ofertas'
      fullPath: '/negocio/ofertas'
      preLoaderRoute: typeof AuthenticatedNegocioOfertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claim/$drawDate': {
      id: '/_authenticated/claim/$drawDate'
      path: '/claim/$drawDate'
      fullPath: '/claim/$drawDate'
      preLoaderRoute: typeof AuthenticatedClaimDrawDateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suggestions': {
      id: '/_authenticated/admin/suggestions'
      path: '/admin/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AuthenticatedAdminSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/repartidores': {
      id: '/_authenticated/admin/repartidores'
      path: '/admin/repartidores'
      fullPath: '/admin/repartidores'
      preLoaderRoute: typeof AuthenticatedAdminRepartidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/deliveries': {
      id: '/_authenticated/admin/deliveries'
      path: '/admin/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AuthenticatedAdminDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-draw-tick': {
      id: '/api/public/hooks/test-draw-tick'
      path: '/api/public/hooks/test-draw-tick'
      fullPath: '/api/public/hooks/test-draw-tick'
      preLoaderRoute: typeof ApiPublicHooksTestDrawTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/security-alert': {
      id: '/api/public/hooks/security-alert'
      path: '/api/public/hooks/security-alert'
      fullPath: '/api/public/hooks/security-alert'
      preLoaderRoute: typeof ApiPublicHooksSecurityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-daily-draw': {
      id: '/api/public/hooks/run-daily-draw'
      path: '/api/public/hooks/run-daily-draw'
      fullPath: '/api/public/hooks/run-daily-draw'
      preLoaderRoute: typeof ApiPublicHooksRunDailyDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-winner': {
      id: '/api/public/hooks/notify-winner'
      path: '/api/public/hooks/notify-winner'
      fullPath: '/api/public/hooks/notify-winner'
      preLoaderRoute: typeof ApiPublicHooksNotifyWinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-pre-draw': {
      id: '/api/public/hooks/notify-pre-draw'
      path: '/api/public/hooks/notify-pre-draw'
      fullPath: '/api/public/hooks/notify-pre-draw'
      preLoaderRoute: typeof ApiPublicHooksNotifyPreDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup-prune': {
      id: '/api/public/hooks/backup-prune'
      path: '/api/public/hooks/backup-prune'
      fullPath: '/api/public/hooks/backup-prune'
      preLoaderRoute: typeof ApiPublicHooksBackupPruneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup-csv': {
      id: '/api/public/hooks/backup-csv'
      path: '/api/public/hooks/backup-csv'
      fullPath: '/api/public/hooks/backup-csv'
      preLoaderRoute: typeof ApiPublicHooksBackupCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedido/$id/seguimiento': {
      id: '/_authenticated/pedido/$id/seguimiento'
      path: '/pedido/$id/seguimiento'
      fullPath: '/pedido/$id/seguimiento'
      preLoaderRoute: typeof AuthenticatedPedidoIdSeguimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedido/$id/calificar': {
      id: '/_authenticated/pedido/$id/calificar'
      path: '/pedido/$id/calificar'
      fullPath: '/pedido/$id/calificar'
      preLoaderRoute: typeof AuthenticatedPedidoIdCalificarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repartidor/pedido/$id/resumen': {
      id: '/_authenticated/repartidor/pedido/$id/resumen'
      path: '/pedido/$id/resumen'
      fullPath: '/repartidor/pedido/$id/resumen'
      preLoaderRoute: typeof AuthenticatedRepartidorPedidoIdResumenRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/repartidor/pedido/$id/navegacion': {
      id: '/_authenticated/repartidor/pedido/$id/navegacion'
      path: '/pedido/$id/navegacion'
      fullPath: '/repartidor/pedido/$id/navegacion'
      preLoaderRoute: typeof AuthenticatedRepartidorPedidoIdNavegacionRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
    '/_authenticated/repartidor/pedido/$id/completado': {
      id: '/_authenticated/repartidor/pedido/$id/completado'
      path: '/pedido/$id/completado'
      fullPath: '/repartidor/pedido/$id/completado'
      preLoaderRoute: typeof AuthenticatedRepartidorPedidoIdCompletadoRouteImport
      parentRoute: typeof AuthenticatedRepartidorRoute
    }
  }
}

interface AuthenticatedRepartidorRouteChildren {
  AuthenticatedRepartidorCalificacionesRoute: typeof AuthenticatedRepartidorCalificacionesRoute
  AuthenticatedRepartidorFacturasRoute: typeof AuthenticatedRepartidorFacturasRoute
  AuthenticatedRepartidorOnboardingRoute: typeof AuthenticatedRepartidorOnboardingRoute
  AuthenticatedRepartidorWalletRoute: typeof AuthenticatedRepartidorWalletRoute
  AuthenticatedRepartidorIndexRoute: typeof AuthenticatedRepartidorIndexRoute
  AuthenticatedRepartidorPedidoIdCompletadoRoute: typeof AuthenticatedRepartidorPedidoIdCompletadoRoute
  AuthenticatedRepartidorPedidoIdNavegacionRoute: typeof AuthenticatedRepartidorPedidoIdNavegacionRoute
  AuthenticatedRepartidorPedidoIdResumenRoute: typeof AuthenticatedRepartidorPedidoIdResumenRoute
}

const AuthenticatedRepartidorRouteChildren: AuthenticatedRepartidorRouteChildren =
  {
    AuthenticatedRepartidorCalificacionesRoute:
      AuthenticatedRepartidorCalificacionesRoute,
    AuthenticatedRepartidorFacturasRoute: AuthenticatedRepartidorFacturasRoute,
    AuthenticatedRepartidorOnboardingRoute:
      AuthenticatedRepartidorOnboardingRoute,
    AuthenticatedRepartidorWalletRoute: AuthenticatedRepartidorWalletRoute,
    AuthenticatedRepartidorIndexRoute: AuthenticatedRepartidorIndexRoute,
    AuthenticatedRepartidorPedidoIdCompletadoRoute:
      AuthenticatedRepartidorPedidoIdCompletadoRoute,
    AuthenticatedRepartidorPedidoIdNavegacionRoute:
      AuthenticatedRepartidorPedidoIdNavegacionRoute,
    AuthenticatedRepartidorPedidoIdResumenRoute:
      AuthenticatedRepartidorPedidoIdResumenRoute,
  }

const AuthenticatedRepartidorRouteWithChildren =
  AuthenticatedRepartidorRoute._addFileChildren(
    AuthenticatedRepartidorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedRepartidorRoute: typeof AuthenticatedRepartidorRouteWithChildren
  AuthenticatedSuggestionsRoute: typeof AuthenticatedSuggestionsRoute
  AuthenticatedAdminDeliveriesRoute: typeof AuthenticatedAdminDeliveriesRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminRepartidoresRoute: typeof AuthenticatedAdminRepartidoresRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSuggestionsRoute: typeof AuthenticatedAdminSuggestionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedClaimDrawDateRoute: typeof AuthenticatedClaimDrawDateRoute
  AuthenticatedNegocioOfertasRoute: typeof AuthenticatedNegocioOfertasRoute
  AuthenticatedNegocioProductosRoute: typeof AuthenticatedNegocioProductosRoute
  AuthenticatedNegocioIndexRoute: typeof AuthenticatedNegocioIndexRoute
  AuthenticatedPedidoIdCalificarRoute: typeof AuthenticatedPedidoIdCalificarRoute
  AuthenticatedPedidoIdSeguimientoRoute: typeof AuthenticatedPedidoIdSeguimientoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedRepartidorRoute: AuthenticatedRepartidorRouteWithChildren,
  AuthenticatedSuggestionsRoute: AuthenticatedSuggestionsRoute,
  AuthenticatedAdminDeliveriesRoute: AuthenticatedAdminDeliveriesRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedAdminRepartidoresRoute: AuthenticatedAdminRepartidoresRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSuggestionsRoute: AuthenticatedAdminSuggestionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedClaimDrawDateRoute: AuthenticatedClaimDrawDateRoute,
  AuthenticatedNegocioOfertasRoute: AuthenticatedNegocioOfertasRoute,
  AuthenticatedNegocioProductosRoute: AuthenticatedNegocioProductosRoute,
  AuthenticatedNegocioIndexRoute: AuthenticatedNegocioIndexRoute,
  AuthenticatedPedidoIdCalificarRoute: AuthenticatedPedidoIdCalificarRoute,
  AuthenticatedPedidoIdSeguimientoRoute: AuthenticatedPedidoIdSeguimientoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminSweepstakesRouteChildren {
  AdminSweepstakesWinnersRoute: typeof AdminSweepstakesWinnersRoute
}

const AdminSweepstakesRouteChildren: AdminSweepstakesRouteChildren = {
  AdminSweepstakesWinnersRoute: AdminSweepstakesWinnersRoute,
}

const AdminSweepstakesRouteWithChildren =
  AdminSweepstakesRoute._addFileChildren(AdminSweepstakesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  DemoRoute: DemoRoute,
  DomainsRoute: DomainsRoute,
  DonateRoute: DonateRoute,
  ExploreRoute: ExploreRoute,
  HistorialRoute: HistorialRoute,
  MenuRoute: MenuRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProfileRoute: ProfileRoute,
  RepartidoresRoute: RepartidoresRoute,
  RuletaRoute: RuletaRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  SweepstakesRulesRoute: SweepstakesRulesRoute,
  TerminosRoute: TerminosRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminSweepstakesRoute: AdminSweepstakesRouteWithChildren,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  NegociosRegistroRoute: NegociosRegistroRoute,
  ProductHandleRoute: ProductHandleRoute,
  ReelReelIdRoute: ReelReelIdRoute,
  ApiPublicDomainCheckRoute: ApiPublicDomainCheckRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksBackupCsvRoute: ApiPublicHooksBackupCsvRoute,
  ApiPublicHooksBackupPruneRoute: ApiPublicHooksBackupPruneRoute,
  ApiPublicHooksNotifyPreDrawRoute: ApiPublicHooksNotifyPreDrawRoute,
  ApiPublicHooksNotifyWinnerRoute: ApiPublicHooksNotifyWinnerRoute,
  ApiPublicHooksRunDailyDrawRoute: ApiPublicHooksRunDailyDrawRoute,
  ApiPublicHooksSecurityAlertRoute: ApiPublicHooksSecurityAlertRoute,
  ApiPublicHooksTestDrawTickRoute: ApiPublicHooksTestDrawTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
