// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oyvbxkluvkrljvewrgue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dmJ4a2x1dmtybGp2ZXdyZ3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMTMxNDgsImV4cCI6MjA5OTc4OTE0OH0.9Djx2uKZbmk3-zacREE0T0V2ELx7vIc60_3qWcdcob4";

// NOTE: types.ts currently reflects only the freshly-swapped Supabase project
// (which is nearly empty). Using the untyped SupabaseClient here keeps the app
// buildable while the schema bundle is being applied to the new project.
// Once the migrations run and types.ts is regenerated, restore the typed
// `createClient<Database>` signature.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const isBrowser = typeof window !== "undefined";
export const supabase: SupabaseClient<any, "public", any> = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: isBrowser ? window.localStorage : undefined,
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
      detectSessionInUrl: isBrowser,
    },
  },
);