// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyvbxkluvkrljvewrgue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dmJ4a2x1dmtybGp2ZXdyZ3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMTMxNDgsImV4cCI6MjA5OTc4OTE0OH0.9Djx2uKZbmk3-zacREE0T0V2ELx7vIc60_3qWcdcob4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});